workouts = [
    {
        "name": "squats",
        "body_part": "legs",
        "type": "compound",
        "goal_type": "strength gain",
    },
    {
        "name": "leg extensions",
        "body_part": "legs",
        "type": "accessory",
        "goal_type": "muscle gain",
    },
    {
        "name": "hamstring curl",
        "body_part": "legs",
        "type": "accessory",
        "goal_type": "muscle gain",
    },
    {
        "name": "lunges",
        "body_part": "legs",
        "type": "accessory",
        "goal_type": "muscle gain",
    },
    {
        "name": "leg press",
        "body_part": "legs",
        "type": "compound",
        "goal_type": "strength gain",
    },
    {
        "name": "calf raises",
        "body_part": "legs",
        "type": "accessory",
        "goal_type": "muscle gain",
    },
    {
        "name": "bench press",
        "body_part": "chest",
        "type": "compound",
        "goal_type": "strength gain",
    },
    {
        "name": "push-ups",
        "body_part": "chest",
        "type": "compound",
        "goal_type": "strength gain",
    },
    {
        "name": "dips",
        "body_part": "chest",
        "type": "accessory",
        "goal_type": "muscle gain",
    },
    {
        "name": "pec deck fly",
        "body_part": "chest",
        "type": "accessory",
        "goal_type": "muscle gain",
    },
    {
        "name": "incline dumbbell bench press",
        "body_part": "chest",
        "type": "compound",
        "goal_type": "strength gain",
    },
    {
        "name": "cable fly",
        "body_part": "chest",
        "type": "accessory",
        "goal_type": "muscle gain",
    },
    {
        "name": "bicep curl",
        "body_part": "arms",
        "type": "accessory",
        "goal_type": "muscle gain",
    },
    {
        "name": "hammer curls",
        "body_part": "arms",
        "type": "accessory",
        "goal_type": "muscle gain",
    },
    {
        "name": "skull crushers",
        "body_part": "arms",
        "type": "accessory",
        "goal_type": "muscle gain",
    },
    {
        "name": "tricep extensions",
        "body_part": "arms",
        "type": "accessory",
        "goal_type": "muscle gain",
    },
    {
        "name": "overhead press",
        "body_part": "shoulders",
        "type": "compound",
        "goal_type": "strength gain",
    },
    {
        "name": "front raises",
        "body_part": "shoulders",
        "type": "accessory",
        "goal_type": "muscle gain",
    },
    {
        "name": "shrugs",
        "body_part": "shoulders",
        "type": "accessory",
        "goal_type": "muscle gain",
    },
    {
        "name": "arnold press",
        "body_part": "shoulders",
        "type": "accessory",
        "goal_type": "muscle gain",
    },
    {
        "name": "lat raises",
        "body_part": "shoulders",
        "type": "accessory",
        "goal_type": "muscle gain",
    },
    {
        "name": "deadlifts",
        "body_part": "back",
        "type": "compound",
        "goal_type": "strength gain",
    },
    {
        "name": "bent-over rows",
        "body_part": "back",
        "type": "compound",
        "goal_type": "strength gain",
    },
    {
        "name": "pull-ups",
        "body_part": "back",
        "type": "compound",
        "goal_type": "strength gain",
    },
    {
        "name": "lat pulldown",
        "body_part": "back",
        "type": "accessory",
        "goal_type": "muscle gain",
    },
    {
        "name": "rows",
        "body_part": "back",
        "type": "accessory",
        "goal_type": "muscle gain",
    },
]